# Docker Comppse Version
version: "3"

services:
    app:
        build : ./php
        volumes:
            - ./backend:/work
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./backend:/work
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

        working_dir: /work
